### ISSUE TITLE
Can't start the game on a fresh Ubuntu Install 

### ISSUE THREAD

**Issue by prempador** [hovgaardgames/startupcompany#174]
Version 7, 8

Here is the error code: 

```
module.js:457
    throw err;
    ^
Error: Cannot find module '/home/prempador/Downloads/StartupCompany-beta8-1-linux-x64/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3
```

**Comment by jhovgaard** [comment]
Was caused by permissions issues. Fixed by tar.gz package instead.
